#!/bin/bash
#SBATCH --nodes=1                    
#SBATCH --ntasks=2                  
#SBATCH --mem=2G                  
#SBATCH --time=4-0:00                
#SBATCH --output=slurm.%j.out        
#SBATCH --error=slurm.%j.err          
#SBATCH --mail-type=BEGIN,END,FAIL         


module load hpc-env/13.1
module load Nextflow/23.10.0

#all the --bed* options are set to false. Only add these options if you ran 3' endseq analysis before
nextflow run main.nf --reads '../data/*.R{1,2}.RUN0076.L2.fastq.gz' --bed_prox_rep_pA_composite_u170k 'bedfiles/proximal_pA_comp_rep_u170k.bed' --bed_prox_rep_pA_composite_u1c 'bedfiles/proximal_pA_comp_rep_u1c.bed' --bed_background_rnd_intron 'bedfiles/bed_position_at_onethird_of_all_introns.bed' --bed_background_distal_pAs 'bedfiles/non_affected_WT_consensus_pA_sites.bed' --bed_all_introns 'bedfiles/bed_all_introns_atrtd3.bed' --bed_distal_pA_where_comp_rep_u1c 'bedfiles/distal_pA_where_comp_rep_u1c.bed' --bed_distal_pA_where_comp_rep_u170k 'bedfiles/distal_pA_where_comp_rep_u170k.bed' -resume
